---
- name: Start Azure VM
  hosts: localhost
  connection: local

  tasks:
  - name: Start the virtual machine
    azure_rm_virtualmachine:
      resource_group: azure-poc-ansible
      name: Azure-ansible-VM01
